Dev den
simonpforster/client-backend pull request #5
Opened 2021-06-29 14:52 UTC by Denis-Andrei

deleteClient method created + tests

2021-06-29 14:57 UTC, simonpforster requested changes

2021-06-29 14:57 UTC, simonpforster commented on app/repositories/ClientRepository.scala
> +	def delete(crn: String): Future[Boolean] = collection.find(equal("crn", crn)).toFuture().flatMap(client => {
The find call is unnecessary, it was used in the other method to check the different outcomes of that call but here there is only delete or not deleted so we can simplify it by removing the find.

2021-06-30 07:13 UTC, simonpforster approved these changes

2021-06-30 07:15 UTC, JakeReidPersonal approved these changes

2021-06-30 07:15 UTC, merged